/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forme;

import Kod.Main;
import KlaseTablica.Dolazak;
import KlaseTablica.Student;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author Emanuel
 */
public class FormaPregledDolazaka extends javax.swing.JDialog {

    /**
     * Creates new form FormaImenikDjelatnici
     */
    
 
    
    

   
    public FormaPregledDolazaka() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setModal(true);
        this.napuniTablicu();
       this.setTitle("Pregled dolazaka");
        
       
    }
    
    public void napuniTablicu()
    {
    
        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");  
         
        
        
        int k = Main.formaPrijava.glavnaforma.dolasci.getTablica().getSelectedRow();
        TableModel model = Main.formaPrijava.glavnaforma.dolasci.getTablica().getModel();
      
        String jmbag =  model.getValueAt(k,0).toString();

        String idKolegij = Main.formaPrijava.glavnaforma.odabraniKolegijID;
         
        
        System.out.println(jmbag+" "+idKolegij);
        
        
        ArrayList <Dolazak> dolasci = Main.db.dohvatiStudentDolaske(jmbag,idKolegij);
       
        DefaultTableModel model_ = (DefaultTableModel) this.tablica.getModel();
        
        Object [] row = new Object [5];
        
        for(int i=0;i<dolasci.size();i++)
        {
            row[0]=dolasci.get(i).getTipNastava();
            row[1]=dolasci.get(i).getOpis();
            Date datum =dolasci.get(i).getDatumOdrz();
            String strDatum = dateFormat.format(datum); 
            row[2]=strDatum;
            row[3]=dolasci.get(i).getObavezno();
            row[4]=dolasci.get(i).getPrisutan();
      
           
            model_.addRow(row);
        }
      
    }
    
     
        public void ocistiTablicu()
        {
        DefaultTableModel model = (DefaultTableModel) tablica.getModel();
        model.setRowCount(0); 
        }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxRed1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablica = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jCheckBoxRed1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jCheckBoxRed1.setForeground(new java.awt.Color(141, 0, 51));
        jCheckBoxRed1.setSelected(true);
        jCheckBoxRed1.setText("Redovni studenti");
        jCheckBoxRed1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxRed1ItemStateChanged(evt);
            }
        });
        jCheckBoxRed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRed1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        tablica.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tip nastave", "Opis", "Datum održavanja", "Obavezno", "Prisutan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablica.setGridColor(new java.awt.Color(0, 0, 0));
        tablica.setRowHeight(22);
        tablica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablicaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablica);
        if (tablica.getColumnModel().getColumnCount() > 0) {
            tablica.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(141, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxRed1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxRed1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxRed1ItemStateChanged

    private void jCheckBoxRed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRed1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxRed1ActionPerformed

    private void tablicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablicaMouseClicked

    }//GEN-LAST:event_tablicaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPregledDolazaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPregledDolazaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPregledDolazaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPregledDolazaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
             
               
                
      
            }
        });
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getTablica() {
        return tablica;
    }

    public void setTablica(JTable tablica) {
        this.tablica = tablica;
    }
    


    public JCheckBox getjCheckBoxRed1() {
        return jCheckBoxRed1;
    }


    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxRed1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablica;
    // End of variables declaration//GEN-END:variables
}
