/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forme;

import Kod.Main;
import KlaseTablica.Student;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author Emanuel
 */
public class FormaKolegijNastavaDolasci extends javax.swing.JDialog {

    /**
     * Creates new form FormaImenikDjelatnici
     */
    

   
    public FormaKolegijNastavaDolasci() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setModal(true);
        this.napuniTablicu();
       
        this.setTitle("Dolasci na nastavu");
       
    }
    
    public void napuniTablicu()
    {
         String idKolegij = Main.formaPrijava.glavnaforma.odabraniKolegijID;
        String idNastava = Main.formaPrijava.glavnaforma.nastava.odabranaNastavaID;
        
        ArrayList <Student> studenti = Main.db.dohvatiStudenteDolaske(idNastava,idKolegij);
       
        DefaultTableModel model = (DefaultTableModel) this.tablica.getModel();
        
        Object [] row = new Object [5];
        
        for(int i=0;i<studenti.size();i++)
        {
            row[0]=studenti.get(i).getJmbag();
            row[1]=studenti.get(i).getPrezime();
            row[2]=studenti.get(i).getIme();
            String vrsta = studenti.get(i).getVrsta() == 'I' ? "IZVANREDNI" : "REDOVNI";
            row[3]=vrsta;
            String prisutan = studenti.get(i).isPrisutan() ? "DA" : "NE";
            row[4]=prisutan;
            
           
            model.addRow(row);
        }
      
    }
    
     
        public void ocistiTablicu()
        {
        DefaultTableModel model = (DefaultTableModel) tablica.getModel();
        model.setRowCount(0); 
        }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxRed1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablica = new javax.swing.JTable();
        jCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        jCheckBoxRed1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jCheckBoxRed1.setForeground(new java.awt.Color(141, 0, 51));
        jCheckBoxRed1.setSelected(true);
        jCheckBoxRed1.setText("Redovni studenti");
        jCheckBoxRed1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxRed1ItemStateChanged(evt);
            }
        });
        jCheckBoxRed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRed1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        tablica.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jmbag", "Prezime", "Ime", "Vrsta", "Prisutan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablica.setGridColor(new java.awt.Color(0, 0, 0));
        tablica.setRowHeight(22);
        tablica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablicaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablica);
        if (tablica.getColumnModel().getColumnCount() > 0) {
            tablica.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        jCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jCheckBox.setForeground(new java.awt.Color(141, 0, 51));
        jCheckBox.setSelected(true);
        jCheckBox.setText("Prisutan");
        jCheckBox.setEnabled(false);
        jCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxItemStateChanged(evt);
            }
        });
        jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(141, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxItemStateChanged
            
  
      
    }//GEN-LAST:event_jCheckBoxItemStateChanged

    private void jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActionPerformed
     
             boolean oznacen = jCheckBox.isSelected();
        String prisutan = oznacen ? "DA" : "NE";
        
       String idNastava = Main.formaPrijava.glavnaforma.nastava.odabranaNastavaID;
       
          int i = tablica.getSelectedRow();
        TableModel model = tablica.getModel();     
        String jmbag = model.getValueAt(i,0).toString();
        Main.db.unosPrisutnosti(jmbag, idNastava, prisutan);
        String idKolegij = Main.formaPrijava.glavnaforma.odabraniKolegijID; 
        Main.db.izvediProcPostaviBrPrisut(idNastava, idKolegij);
        this.ocistiTablicu();
        this.napuniTablicu();
        Main.formaPrijava.glavnaforma.nastava.getjButton4().setEnabled(true);
    }//GEN-LAST:event_jCheckBoxActionPerformed

    private void jCheckBoxRed1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxRed1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxRed1ItemStateChanged

    private void jCheckBoxRed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRed1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxRed1ActionPerformed

    private void tablicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablicaMouseClicked
         int i = tablica.getSelectedRow();
      TableModel model = tablica.getModel();
      
      String prezime,ime,prisutan;
     prezime =  model.getValueAt(i,1).toString();
      ime = model.getValueAt(i,2).toString();
      prisutan =  model.getValueAt(i,4).toString();
      
      jLabel1.setText(prezime+" "+ime);
      jCheckBox.setEnabled(true);
      if(prisutan.equals("DA"))
      {
          jCheckBox.setSelected(true);
      }
      else
      {
          jCheckBox.setSelected(false);
      }

     
      
    }//GEN-LAST:event_tablicaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaKolegijNastavaDolasci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaKolegijNastavaDolasci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaKolegijNastavaDolasci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaKolegijNastavaDolasci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
             
               
                
      
            }
        });
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getTablica() {
        return tablica;
    }

    public void setTablica(JTable tablica) {
        this.tablica = tablica;
    }
    
   

    public JCheckBox getjCheckBoxRed() {
        return jCheckBox;
    }

    public void setjCheckBoxRed(JCheckBox jCheckBoxRed) {
        this.jCheckBox = jCheckBoxRed;
    }

    public JCheckBox getjCheckBoxRed1() {
        return jCheckBoxRed1;
    }


    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JCheckBox jCheckBoxRed1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablica;
    // End of variables declaration//GEN-END:variables
}
