/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forme;


import Kod.Main;
import KlaseTablica.Lokacija;
import KlaseTablica.Nastava;
import KlaseTablica.TipNastava;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Emanuel
 */
public class FormaKolegijNastava extends javax.swing.JDialog {

     
     String odabraniKolegijID = Main.formaPrijava.glavnaforma.odabraniKolegijID;
     String odabraniTipNastave;
     String odabranaNastavaID;
     
     boolean slusaj = false;
     
      ArrayList <TipNastava> tipoviNastave = new ArrayList();
     
      ArrayList <Lokacija> lokacije = new ArrayList();

      
         
    public FormaKolegijNastava() {
        initComponents();
         this.setLocationRelativeTo(null);
         this.setModal(true);
         
        this.setTitle("Nastava");
    
        napuniComboBox();
        napuniTablicu();
     
    }
    
    
    
    public void napuniComboBox()
    {
    
    tipoviNastave = Main.db.dohvatiTipNastave();
    
   
    if(tipoviNastave.isEmpty())
    {
        JOptionPane.showMessageDialog(this,"Nije unesen niti jedan tip nastave!","Nema tipova nastave", JOptionPane.WARNING_MESSAGE);
        this.jComboBox1.setEnabled(false);
    }
    else
    {
        for(int i=0; i < tipoviNastave.size();i++)
        {
            String labela = tipoviNastave.get(i).getNaziv();
            if(tipoviNastave.get(i).isObavezno())
            {
                labela += " - obavez. ";
               
            }
            else
            {
                labela += " - neobavez. ";
                
            }
            
            jComboBox1.addItem(labela);
         
        }
                      
        
        jComboBox1.setSelectedIndex(0);
        odabraniTipNastave = jComboBox1.getSelectedItem().toString(); 
        

        slusaj = true;
    }
    
    }
    
    public void napuniTablicu()
    {
        ArrayList <Nastava> podaci = Main.db.dohvatiKolegijNastave(odabraniTipNastave,odabraniKolegijID);
        

        
        DefaultTableModel model = (DefaultTableModel) this.tablica.getModel();
        
        Object [] row = new Object [9];
        
        for(int i=0;i<podaci.size();i++)
        {
            row[0]=podaci.get(i).getIdNastava();
            row[1]=podaci.get(i).getOpis();
            Date datum=podaci.get(i).getDatumVrijeme().getDatum1();
            DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");  
            row[2] = dateFormat.format(datum);
            row[3]=podaci.get(i).getDatumVrijeme().getVrijeme1();
            row[4]=podaci.get(i).getDatumVrijeme().getVrijeme2();
            row[5]=podaci.get(i).getProstorija();
            row[6]=podaci.get(i).getLokacija();
            row[7]=podaci.get(i).getDjelatnik();
            row[8]=podaci.get(i).getBrPrisutnih();
           
            
            model.addRow(row);
        }
        tablica.getColumnModel().getColumn(0).setMinWidth(0);
        tablica.getColumnModel().getColumn(0).setMaxWidth(0);
        tablica.getColumnModel().getColumn(0).setWidth(0);
        
          
        }
        
        public void ocistiTablicu()
        {
        DefaultTableModel model = (DefaultTableModel) tablica.getModel();
        model.setRowCount(0); 
        }
       
        
  

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablica = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(600, 900));
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        tablica.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Opis", "Datum", "Od", "Do", "Prostorija", "Lokacija", "Djelatnik", "Broj prisut."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablica.setGridColor(new java.awt.Color(0, 0, 0));
        tablica.setRowHeight(22);
        tablica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablicaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablicaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablica);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(141, 0, 51));
        jButton1.setText("NOVI UNOS");
        jButton1.setToolTipText("");
        jButton1.setPreferredSize(new java.awt.Dimension(111, 33));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setActionCommand("");
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(141, 0, 51));
        jButton2.setText("BRISANJE");
        jButton2.setEnabled(false);
        jButton2.setPreferredSize(new java.awt.Dimension(111, 33));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(141, 0, 51));
        jButton3.setText("UNOS PRISUSTVA");
        jButton3.setEnabled(false);
        jButton3.setPreferredSize(new java.awt.Dimension(111, 33));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(141, 0, 51));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(141, 0, 51));
        jButton4.setText("OSVJEŽAVANJE TABLICE");
        jButton4.setEnabled(false);
        jButton4.setPreferredSize(new java.awt.Dimension(111, 33));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jButton1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        FormaUnosNastava forma = new FormaUnosNastava();
        forma.getjLabelKolegij().setText(Main.formaPrijava.glavnaforma.getjLabel7().getText());
        forma.getjLabelTipNastave().setText(odabraniTipNastave);
                
       lokacije = Main.db.dohvatiLokacije();
         
        
        if(lokacije.isEmpty())
    {
        JOptionPane.showMessageDialog(this,"Nije unesena niti jedna lokacija","Nema lokacija", JOptionPane.WARNING_MESSAGE);
        forma.getjComboBox1().setEnabled(false);
    }
    else
    {
        for(int i=0; i < lokacije.size();i++)
        {
            String naziv = lokacije.get(i).getLokacijaNaziv();
            String adresa = lokacije.get(i).getLokacijaAdresa();
            String mjesto = lokacije.get(i).getMjestoNaziv();
            Integer id = lokacije.get(i).getLokacijaId();
           
            
            forma.getjComboBox1().addItem(naziv+" - "+adresa+", "+mjesto);
     
        }
      
    }
   
        forma.setVisible(true);
   
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablicaMouseClicked

        String opis,datumString;
      
        
      int i = tablica.getSelectedRow();
      TableModel model = tablica.getModel();
      
      opis =  model.getValueAt(i,1).toString();
      datumString = model.getValueAt(i,2).toString();
      odabranaNastavaID = model.getValueAt(i,0).toString();
      DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");  
      
    
      jLabel1.setText(opis+" - "+datumString);
      jButton2.setEnabled(true);
      jButton3.setEnabled(true);
      
    }//GEN-LAST:event_tablicaMouseClicked

    private void tablicaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablicaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablicaMousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
     
    if(slusaj == true)
    {
    odabraniTipNastave = jComboBox1.getSelectedItem().toString();
    ocistiTablicu();
    napuniTablicu();
    }
   
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // BRISANJE NASTAVE
       String opis;
       
       
         if (JOptionPane.showConfirmDialog(this, 
            "Jeste li sigurni da želite obrisati ovaj unos nastave?", "Brisanje nastave", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
       Main.db.brisanjeDolazaka(this.odabranaNastavaID);

       Main.db.brisanjeNastave(this.odabranaNastavaID);
       
       odabranaNastavaID = null;
       
       jLabel1.setText(null);
      jButton3.setEnabled(false);
      jButton2.setEnabled(false);  
      
    if(slusaj == true)
    {
    odabraniTipNastave = jComboBox1.getSelectedItem().toString();
    ocistiTablicu();
    napuniTablicu();
    }
            }
         else{
             // Ne učini ništa
         }     
      
      
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // DOLASCI
        
        FormaKolegijNastavaDolasci forma = new FormaKolegijNastavaDolasci();
    
        forma.setVisible(true);
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
       
        
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       this.ocistiTablicu();
       this.napuniTablicu();
       this.jButton4.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaKolegijNastava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaKolegijNastava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaKolegijNastava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaKolegijNastava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
             
               
                
      
            }
        });
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public String getOdabraniKolegijID() {
        return odabraniKolegijID;
    }

    public void setOdabraniKolegijID(String odabraniKolegijID) {
        this.odabraniKolegijID = odabraniKolegijID;
    }

    public String getOdabraniTipNastave() {
        return odabraniTipNastave;
    }

    public void setOdabraniTipNastave(String odabraniTipNastave) {
        this.odabraniTipNastave = odabraniTipNastave;
    }

    public String getOdabranaNastavaID() {
        return odabranaNastavaID;
    }

    public void setOdabranaNastavaID(String odabranaNastavaID) {
        this.odabranaNastavaID = odabranaNastavaID;
    }

    public boolean isSlusaj() {
        return slusaj;
    }

    public void setSlusaj(boolean slusaj) {
        this.slusaj = slusaj;
    }

    public ArrayList<TipNastava> getTipoviNastave() {
        return tipoviNastave;
    }

    public void setTipoviNastave(ArrayList<TipNastava> tipoviNastave) {
        this.tipoviNastave = tipoviNastave;
    }

    public ArrayList<Lokacija> getLokacije() {
        return lokacije;
    }

    public void setLokacije(ArrayList<Lokacija> lokacije) {
        this.lokacije = lokacije;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JButton getjButton3() {
        return jButton3;
    }

    public void setjButton3(JButton jButton3) {
        this.jButton3 = jButton3;
    }

    public JButton getjButton4() {
        return jButton4;
    }

    public void setjButton4(JButton jButton4) {
        this.jButton4 = jButton4;
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    
    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getTablica() {
        return tablica;
    }

    public void setTablica(JTable tablica) {
        this.tablica = tablica;
    }



    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablica;
    // End of variables declaration//GEN-END:variables
}
