/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forme;

import Kod.Main;
import KlaseTablica.Student;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author Emanuel
 */
public class FormaPregledDolazakaStudenti extends javax.swing.JDialog {

    /**
     * Creates new form FormaImenikDjelatnici
     */
    

   
    public FormaPregledDolazakaStudenti() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setModal(true);
        this.napuniTablicu();
       this.setTitle("Pregled dolazaka");
        
       
    }
    
    public void napuniTablicu()
    {
         String idKolegij = Main.formaPrijava.glavnaforma.odabraniKolegijID;
        
        
        ArrayList <Student> studenti = Main.db.dohvatiKolegijStudente(idKolegij);
       
        DefaultTableModel model = (DefaultTableModel) this.tablica.getModel();
        
        Object [] row = new Object [4];
        
        for(int i=0;i<studenti.size();i++)
        {
            row[0]=studenti.get(i).getJmbag();
            row[1]=studenti.get(i).getPrezime();
            row[2]=studenti.get(i).getIme();
            String vrsta = studenti.get(i).getVrsta() == 'I' ? "IZVANREDNI" : "REDOVNI";
            row[3]=vrsta;
            
            model.addRow(row);
        }
      
    }
    
     
        public void ocistiTablicu()
        {
        DefaultTableModel model = (DefaultTableModel) tablica.getModel();
        model.setRowCount(0); 
        }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxRed1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablica = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jCheckBoxRed1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jCheckBoxRed1.setForeground(new java.awt.Color(141, 0, 51));
        jCheckBoxRed1.setSelected(true);
        jCheckBoxRed1.setText("Redovni studenti");
        jCheckBoxRed1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxRed1ItemStateChanged(evt);
            }
        });
        jCheckBoxRed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRed1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        tablica.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jmbag", "Prezime", "Ime", "Vrsta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablica.setGridColor(new java.awt.Color(0, 0, 0));
        tablica.setRowHeight(22);
        tablica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablicaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablica);
        if (tablica.getColumnModel().getColumnCount() > 0) {
            tablica.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(141, 0, 51));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(141, 0, 51));
        jButton2.setText("DOLASCI NA NASTAVU");
        jButton2.setEnabled(false);
        jButton2.setPreferredSize(new java.awt.Dimension(111, 33));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxRed1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxRed1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxRed1ItemStateChanged

    private void jCheckBoxRed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRed1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxRed1ActionPerformed

    private void tablicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablicaMouseClicked
      
        int i = tablica.getSelectedRow();
      TableModel model = tablica.getModel();
      
      String prezime,ime;
     prezime =  model.getValueAt(i,1).toString();
      ime = model.getValueAt(i,2).toString();
    
      
      jLabel1.setText(prezime+" "+ime);
      jButton2.setEnabled(true);
      
  

     
      
    }//GEN-LAST:event_tablicaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        FormaPregledDolazaka forma = new FormaPregledDolazaka();
      int i = tablica.getSelectedRow();
      TableModel model = tablica.getModel();
      
      String jmbag,prezime,ime;
      jmbag =  model.getValueAt(i,3).toString();
      
          
      prezime =  model.getValueAt(i,1).toString();
      ime = model.getValueAt(i,2).toString();
    
      
      forma.getjLabel1().setText(prezime+" "+ime);
      forma.setVisible(true);
 
        this.jButton2.setEnabled(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPregledDolazakaStudenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPregledDolazakaStudenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPregledDolazakaStudenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPregledDolazakaStudenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
             
               
                
      
            }
        });
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getTablica() {
        return tablica;
    }

    public void setTablica(JTable tablica) {
        this.tablica = tablica;
    }
    
   



    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxRed1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablica;
    // End of variables declaration//GEN-END:variables
}
