/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.academus.forme;


import com.academus.tablice.Korisnik;
import com.academus.kod.Main;
import com.academus.tekst.JTextFieldLimit;
import java.text.SimpleDateFormat;
import java.util.Date;



import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author Emanuel
 */
public class FormaPrijava extends javax.swing.JFrame{

    /**
     * Creates new form Prijava
     */
    public FormaPrijava() {
        initComponents();
       SimpleDateFormat formatter = new SimpleDateFormat("dd.MM.yyyy.");  
       Date date = new Date();  
       jLabel4.setText(formatter.format(date));
        
    }
    
    //Objekti forme
    FormaGlavna glavnaforma;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        prijavaGumb = new javax.swing.JButton();
        korisnikLabel = new javax.swing.JLabel();
        lozinkaLabel = new javax.swing.JLabel();
        korisnikInput = new javax.swing.JTextField();
        lozinkaInput = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Academus");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(200, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        prijavaGumb.setBackground(new java.awt.Color(255, 255, 255));
        prijavaGumb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prijavaGumb.setForeground(new java.awt.Color(141, 0, 51));
        prijavaGumb.setText("PRIJAVA");
        prijavaGumb.setBorder(null);
        prijavaGumb.setPreferredSize(new java.awt.Dimension(65, 25));
        prijavaGumb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prijavaGumbActionPerformed(evt);
            }
        });

        korisnikLabel.setBackground(new java.awt.Color(255, 255, 255));
        korisnikLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        korisnikLabel.setForeground(new java.awt.Color(141, 0, 51));
        korisnikLabel.setText("KORISNIK");

        lozinkaLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lozinkaLabel.setForeground(new java.awt.Color(141, 0, 51));
        lozinkaLabel.setText("LOZINKA");

        korisnikInput.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        korisnikInput.setDocument(new com.academus.tekst.JTextFieldLimit(12));
        korisnikInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(141, 0, 51), 3));
        korisnikInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                korisnikInputActionPerformed(evt);
            }
        });

        lozinkaInput.setDocument(new JTextFieldLimit(12) );
        lozinkaInput.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lozinkaInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(141, 0, 51), 3));
        lozinkaInput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.academus.resursi/academus.PNG"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(141, 0, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(141, 0, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(141, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Datum.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(korisnikLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lozinkaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lozinkaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(korisnikInput, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prijavaGumb, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(255, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(korisnikLabel)
                            .addComponent(korisnikInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lozinkaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lozinkaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(prijavaGumb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel4)))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prijavaGumbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prijavaGumbActionPerformed
       
     String korisnickoIme = this.getKorisnikInput().getText();
    
     String lozinka = String.valueOf(this.getLozinkaInput().getPassword());
     
     if(korisnickoIme.isEmpty())
          {
                 JOptionPane.showMessageDialog(this,"Unesite korisničko ime!","Prijava korisnika", JOptionPane.WARNING_MESSAGE);
          }
     
     if(lozinka.isEmpty())
          {
                 JOptionPane.showMessageDialog(this,"Unesite lozinku!","Prijava korisnika", JOptionPane.WARNING_MESSAGE);
          }
     
     if(!lozinka.isEmpty() && !korisnickoIme.isEmpty())
     {  
 
     
     int provjeriUnos = Main.db.dohvatiKorisnik(korisnickoIme, lozinka);
     
        switch (provjeriUnos) {
            case 0:
                JOptionPane.showMessageDialog(this,"Uneseno korisničko ime ne postoji!","Prijava korisnika", JOptionPane.ERROR_MESSAGE);
               this.getKorisnikInput().setText("");
               this.getLozinkaInput().setText("");
               
                break;
            case -1:
                JOptionPane.showMessageDialog(this,"Unesena je pogrešna lozinka!","Prijava korisnika", JOptionPane.ERROR_MESSAGE);
                this.getLozinkaInput().setText("");
                break;
            case 1:
                JOptionPane.showMessageDialog(this,"Uspješna prijava!","Prijava korisnika", JOptionPane.INFORMATION_MESSAGE);
                
                 this.dispose();
                 glavnaforma = new FormaGlavna();
                 
                 glavnaforma.prikaziKomponente();
                 
                 
                break;
            
        }
        
     }
     
     
     
    
     
        
    }//GEN-LAST:event_prijavaGumbActionPerformed

    public JTextField getKorisnikInput() {
        return korisnikInput;
    }

    public JLabel getKorisnikLabel() {
        return korisnikLabel;
    }

    public JPasswordField getLozinkaInput() {
        return lozinkaInput;
    }

    public JLabel getLozinkaLabel() {
        return lozinkaLabel;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public void setLozinkaInput(JPasswordField lozinkaInput) {
        this.lozinkaInput = lozinkaInput;
    }

    public void setLozinkaLabel(JLabel lozinkaLabel) {
        this.lozinkaLabel = lozinkaLabel;
    }

    public void setKorisnikInput(JTextField korisnikInput) {
        this.korisnikInput = korisnikInput;
    }

    public void setKorisnikLabel(JLabel korisnikLabel) {
        this.korisnikLabel = korisnikLabel;
    }
    
    
    

    private void korisnikInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_korisnikInputActionPerformed
        
    }//GEN-LAST:event_korisnikInputActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Main.zatvaranjeDijalog(this);
    }//GEN-LAST:event_formWindowClosing

 
    

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField korisnikInput;
    private javax.swing.JLabel korisnikLabel;
    private javax.swing.JPasswordField lozinkaInput;
    private javax.swing.JLabel lozinkaLabel;
    private javax.swing.JButton prijavaGumb;
    // End of variables declaration//GEN-END:variables
}
