/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.academus.forme;


import com.academus.kod.Main;
import com.academus.tablice.Student;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Emanuel
 */
public class FormaKolegijStudenti extends javax.swing.JDialog {

    /**
     * Creates new form FormaImenikDjelatnici
     */
    
    
     int vrsta = 0;
     boolean redovni=false;
     boolean izvanredni=false;
     
     String odabraniKolegijID = Main.formaPrijava.glavnaforma.odabraniKolegijID;
         
         
    public FormaKolegijStudenti() {
        initComponents();
         this.setLocationRelativeTo(null);
         this.setModal(true);
        
         
          if(jCheckBoxIzv.isSelected())
           izvanredni = true;
            else
            {
           izvanredni = false;
            }
          
          if(jCheckBoxRed.isSelected())
           redovni = true;
            else
            {
           redovni = false;
            }
          
          napuniTablicu();
          
         
    }
    
    
    void ocistiTablicu()
    {
        DefaultTableModel model = (DefaultTableModel) tablica.getModel();
        model.setRowCount(0);   
    }
    
    
    void napuniTablicu()
    {
        
    
     if(redovni == true && izvanredni == false)
         {
             vrsta = 1;
         }
         else if(izvanredni == true && redovni == false)
         {
             vrsta = 2;
         }
         else if(izvanredni == true && redovni == true)
         {
             vrsta = 3;
         }
         else if(izvanredni == false && redovni == false)
         {
             vrsta = 4;
         }
      
         System.out.println("Odabrana vrsta studenat je "+vrsta);
         
      
        ArrayList <Student> studenti = Main.db.dohvatiKolegijStudente(vrsta,odabraniKolegijID);
        
        
        
        DefaultTableModel model = (DefaultTableModel) this.tablica.getModel();
        
        Object [] row = new Object [7];
        
        if(vrsta != 4)
        {
              for(int i=0;i<studenti.size();i++)
        {
            row[0]=i+1;
            row[1]=studenti.get(i).getJmbag();
            row[2]=studenti.get(i).getPrezime();
            row[3]=studenti.get(i).getIme();
            row[4]=studenti.get(i).getEmail();
            row[5]=studenti.get(i).getMobitel();
            String vrstaString = studenti.get(i).getVrsta() == 'R' ? "REDOVNI" : "IZVANREDNI";
            row[6]=vrstaString;
            model.addRow(row);
        }
      
        }
       
        
      
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablica = new javax.swing.JTable();
        jCheckBoxRed = new javax.swing.JCheckBox();
        jCheckBoxIzv = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        tablica.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "R.br.", "Jmbag", "Prezime", "Ime", "E-pošta", "Mobitel", "Vrsta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablica.setGridColor(new java.awt.Color(0, 0, 0));
        tablica.setRowHeight(22);
        jScrollPane2.setViewportView(tablica);
        if (tablica.getColumnModel().getColumnCount() > 0) {
            tablica.getColumnModel().getColumn(0).setPreferredWidth(20);
            tablica.getColumnModel().getColumn(1).setPreferredWidth(50);
        }

        jCheckBoxRed.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBoxRed.setForeground(new java.awt.Color(141, 0, 51));
        jCheckBoxRed.setSelected(true);
        jCheckBoxRed.setText("Redovni studenti");
        jCheckBoxRed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxRedItemStateChanged(evt);
            }
        });
        jCheckBoxRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRedActionPerformed(evt);
            }
        });

        jCheckBoxIzv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBoxIzv.setForeground(new java.awt.Color(141, 0, 51));
        jCheckBoxIzv.setText("Izvanredni studenti");
        jCheckBoxIzv.setActionCommand("");
        jCheckBoxIzv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxIzvItemStateChanged(evt);
            }
        });
        jCheckBoxIzv.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxIzvStateChanged(evt);
            }
        });
        jCheckBoxIzv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIzvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxRed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxIzv)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxRed, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxIzv, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxRedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxRedItemStateChanged
        if(jCheckBoxRed.isSelected())
        {
             redovni = true;
             System.out.println("Opcija odabrana: Redovni");
        }
        else
        {
            redovni = false;
             System.out.println("Opcija poništena: Redovni");
        }
        
        ocistiTablicu();
        napuniTablicu();
       
       

       
    }//GEN-LAST:event_jCheckBoxRedItemStateChanged

    private void jCheckBoxRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxRedActionPerformed

    private void jCheckBoxIzvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxIzvItemStateChanged
        if(jCheckBoxIzv.isSelected())
        {
            izvanredni = true;
            System.out.println("Opcija odabrana: Izvanredni");
        }
       else
        {
            izvanredni = false;
            System.out.println("Opcija poništena: Izvanredni");
        }
        
        ocistiTablicu();
        napuniTablicu();
        
    }//GEN-LAST:event_jCheckBoxIzvItemStateChanged

    private void jCheckBoxIzvStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxIzvStateChanged

    }//GEN-LAST:event_jCheckBoxIzvStateChanged

    private void jCheckBoxIzvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIzvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxIzvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaKolegijStudenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaKolegijStudenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaKolegijStudenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaKolegijStudenti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
             
               
                
      
            }
        });
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getTablica() {
        return tablica;
    }

    public void setTablica(JTable tablica) {
        this.tablica = tablica;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxIzv;
    private javax.swing.JCheckBox jCheckBoxRed;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablica;
    // End of variables declaration//GEN-END:variables
}
