/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.academus.forme;

import com.academus.kod.Main;
import com.toedter.calendar.JDateChooser;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author Emanuel
 */
public class FormaUnosOcjene extends javax.swing.JDialog {

    /**
     * Creates new form FormaUnosOcjene
     */
    
   //Učitane vrijednosti u startu 
    String usmeni;
    String pismeni;
    String konacno;
    
    public FormaUnosOcjene() {
        initComponents();
        this.setModal(true);
         this.setLocationRelativeTo(null);
    }

  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelJMBAG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelPrezime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelIme = new javax.swing.JLabel();
        Vrsta = new javax.swing.JLabel();
        jTextFieldKonacna = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPismeni = new javax.swing.JTextField();
        jTextFieldUsmeni = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Usmeni ispit");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Pismeni ispit");

        jDateChooser1.setDateFormatString("dd.MM.yyyy");
        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDateChooser1.setMaxSelectableDate(new java.util.Date(32503680098000L));
        jDateChooser1.setMinSelectableDate(new java.util.Date(946684898000L));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Datum polaganja");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(141, 0, 51), 3));
        jPanel2.setForeground(new java.awt.Color(141, 0, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(670, 179));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("JMBAG");

        jLabelJMBAG.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelJMBAG.setForeground(new java.awt.Color(141, 0, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Prezime");

        jLabelPrezime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPrezime.setForeground(new java.awt.Color(141, 0, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Ime");

        jLabelIme.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelIme.setForeground(new java.awt.Color(141, 0, 51));

        Vrsta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Vrsta.setForeground(new java.awt.Color(141, 0, 51));
        Vrsta.setText("Vrsta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelPrezime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIme, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jLabelJMBAG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Vrsta, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelJMBAG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(Vrsta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelIme, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTextFieldKonacna.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldKonacna.setForeground(new java.awt.Color(141, 0, 51));
        jTextFieldKonacna.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldKonacna.setDocument(new com.academus.tekst.JTextFieldLimit(1));
        jTextFieldKonacna.setToolTipText("");
        jTextFieldKonacna.setMinimumSize(new java.awt.Dimension(100, 31));
        jTextFieldKonacna.setPreferredSize(new java.awt.Dimension(100, 31));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Konačna ocjena");

        jTextFieldPismeni.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldPismeni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPismeni.setDocument(new com.academus.tekst.JTextFieldLimit(1));
        jTextFieldPismeni.setToolTipText("");
        jTextFieldPismeni.setMinimumSize(new java.awt.Dimension(100, 31));

        jTextFieldUsmeni.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldUsmeni.setDocument(new com.academus.tekst.JTextFieldLimit(1));
        jTextFieldUsmeni.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(141, 0, 51));
        jButton1.setText("UNOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPismeni, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jTextFieldUsmeni)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldKonacna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPismeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsmeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldKonacna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
      
        String u,p,k;
        Date datumPolaganja;
        
        boolean errorOcjene = false;
        boolean errorDatuma = false;
        
        if(!jTextFieldKonacna.getText().equals("1") && !jTextFieldKonacna.getText().equals("2") 
          && !jTextFieldKonacna.getText().equals("3") && !jTextFieldKonacna.getText().equals("4")
          && !jTextFieldKonacna.getText().equals("5") && jTextFieldKonacna.getText() != null && !jTextFieldKonacna.getText().isBlank())
            {
                errorOcjene = true; 
            }
        else if(!jTextFieldUsmeni.getText().equals("1") && !jTextFieldUsmeni.getText().equals("2") 
          && !jTextFieldUsmeni.getText().equals("3") && !jTextFieldUsmeni.getText().equals("4")
          && !jTextFieldUsmeni.getText().equals("5") && jTextFieldKonacna.getText() != null && !jTextFieldUsmeni.getText().isBlank())
        
            {
                errorOcjene = true; 
            }
        else if(!jTextFieldPismeni.getText().equals("1") && !jTextFieldPismeni.getText().equals("2") 
          && !jTextFieldPismeni.getText().equals("3") && !jTextFieldPismeni.getText().equals("4")
          && !jTextFieldPismeni.getText().equals("5") && jTextFieldKonacna.getText() != null && !jTextFieldPismeni.getText().isBlank())
        
            {
                errorOcjene = true; 
            }
        
        if(errorOcjene == true)
        {
            JOptionPane.showMessageDialog(this,"Unesite valjanu ocjenu!","Kriva vrijednost ocjene", JOptionPane.ERROR_MESSAGE);
            jTextFieldUsmeni.setText(usmeni);
            jTextFieldPismeni.setText(pismeni);
            jTextFieldKonacna.setText(konacno);
          
        }
        else
        {
            u = jTextFieldUsmeni.getText();
            p = jTextFieldPismeni.getText();
            k = jTextFieldKonacna.getText();              
            
            
            datumPolaganja = jDateChooser1.getDate();                
            String strDate= null;
           
            if(datumPolaganja != null)
            {
                
                
            try
            {
             DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");  
            strDate = dateFormat.format(datumPolaganja);
            }
            catch(Exception e)
            {      
                
                    System.out.println("Datum nije prošao validaciju!");
                    errorDatuma = true;
                }
                
            }
            
            if(errorDatuma == true)
                
            {
                JOptionPane.showMessageDialog(this,"Unesite valjani datum!","Kriva vrijednost datuma", JOptionPane.ERROR_MESSAGE);
                jDateChooser1.setDate(null);
                
            }
            
            else
            {
                
            if(JOptionPane.showConfirmDialog(this, "Jesti li sigurni da želite unijeti ove vrijednosti?","Unos ocjena",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION)
            {
                 //Podaci su validirani i spremni za unos
                System.out.println("-----UNOS-----");
                System.out.println("Ocjena pismeni: "+p);
                System.out.println("Ocjena usmeni: "+u);
                System.out.println("Ocjena konacna: "+k);
                System.out.println("Datum polaganja: "+strDate);
                System.out.println("---------------");
                
                String jmbag = jLabelJMBAG.getText();
                String idKolegij = Main.formaPrijava.glavnaforma.odabraniKolegijID;
                
                
                Main.db.unosOcjena(jmbag,idKolegij,p,u,k,datumPolaganja);
                
                this.dispose();
                Main.formaPrijava.glavnaforma.ocjene.ocistiTablicu();
                Main.formaPrijava.glavnaforma.ocjene.napuniTablicu();
                
            
            }     
            }
                   
            
        }
        
        
        
        
            
        
       
       
           
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaUnosOcjene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaUnosOcjene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaUnosOcjene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaUnosOcjene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaUnosOcjene().setVisible(true);
                
            }
        });
        
        
    }

    public JButton getjButton1() {
        return jButton1;
    }
    
      public JLabel getVrsta() {
        return Vrsta;
    }

    public void setVrsta(JLabel Vrsta) {
        this.Vrsta = Vrsta;
    }
    

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JDateChooser getjDateChooser1() {
        return jDateChooser1;
    }

    public void setjDateChooser1(JDateChooser jDateChooser1) {
        this.jDateChooser1 = jDateChooser1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabelIme() {
        return jLabelIme;
    }

    public void setjLabelIme(JLabel jLabelIme) {
        this.jLabelIme = jLabelIme;
    }

    public JLabel getjLabelJMBAG() {
        return jLabelJMBAG;
    }

    public void setjLabelJMBAG(JLabel jLabelJMBAG) {
        this.jLabelJMBAG = jLabelJMBAG;
    }

    public JLabel getjLabelPrezime() {
        return jLabelPrezime;
    }

    public void setjLabelPrezime(JLabel jLabelPrezime) {
        this.jLabelPrezime = jLabelPrezime;
    }

    public JTextField getjTextFieldKonacna() {
        return jTextFieldKonacna;
    }

    public void setjTextFieldKonacna(JTextField jTextFieldKonacna) {
        this.jTextFieldKonacna = jTextFieldKonacna;
    }

    public JTextField getjTextFieldPismeni() {
        return jTextFieldPismeni;
    }

    public void setjTextFieldPismeni(JTextField jTextFieldPismeni) {
        this.jTextFieldPismeni = jTextFieldPismeni;
    }

    public JTextField getjTextFieldUsmeni() {
        return jTextFieldUsmeni;
    }

    public void setjTextFieldUsmeni(JTextField jTextFieldUsmeni) {
        this.jTextFieldUsmeni = jTextFieldUsmeni;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Vrsta;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelJMBAG;
    private javax.swing.JLabel jLabelPrezime;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldKonacna;
    private javax.swing.JTextField jTextFieldPismeni;
    private javax.swing.JTextField jTextFieldUsmeni;
    // End of variables declaration//GEN-END:variables
}
